feat(format-number): added component and example
quiches-group/quichtify pull request #14
Opened 2022-05-13 13:24 UTC by ChxGuillaume

2022-05-13 13:27 UTC, MaxenceMottard commented
For example, with crypto-currencies, you won't find fonts that implement them.

2022-05-13 13:28 UTC, MaxenceMottard reviewed
For example, with crypto-currencies, you won't find fonts that implement them.

2022-05-31 21:32 UTC, MrZyr0 requested changes

2022-05-31 21:32 UTC, MrZyr0 commented on src/components/FormatNumber/FormatNumber.vue
> +  <div v-text="formatted" />
Il n'y a pas un markup html précisément pour ça ? Sinon un paragraphe ou un span suivant le contexte me semble plus approprié.

2022-06-03 14:08 UTC, MrZyr0 approved these changes

2022-06-03 14:08 UTC, merged