Card
quiches-group/quichtify pull request #24
Opened 2022-05-31 15:02 UTC by HugoBordais

VueJS card
1st version :
- Basic design
- Basic card

For the next version :
- Improve the design
- Adding button to open or close the card

2022-05-31 21:16 UTC, MrZyr0 requested changes

2022-05-31 21:16 UTC, MrZyr0 commented on src/components/q-card/q-card.scss
> +
Dommage de ne pas utiliser tailwind et d'en faire un fichier séparé. Au vu de la taille ça n'est pas justifié.

2022-05-31 21:16 UTC, MrZyr0 commented on src/components/q-card/q-card.vue
> +  name: 'q-card',
Pas nécéssaire

2022-05-31 21:16 UTC, MrZyr0 commented on src/components/q-card/q-card.vue
> +import './q-card.scss';
Pire truc ça !

2022-06-01 10:45 UTC, HugoBordais commented on src/components/q-card/q-card.scss
> +
C'est horrible, je trouve tailwind vraiment pas fou. Ça vient juste surchargé un code HTML et celui-ci deviendra simplement illisible. On à déjà ce problème avec BootStrap et tout le monde râle.
Le fait de séparer HTML et CSS dans 2 fichiers différents permet plus de lisibilité et facilite le partage avec d'autre.

2022-06-01 10:47 UTC, HugoBordais commented on src/components/q-card/q-card.vue
> +import './q-card.scss';
En lien avec le commentaire précédent.

2022-06-01 20:06 UTC, MrZyr0 commented on src/components/q-card/q-card.scss
> +
Tu peux très bien utiliser tailwind dans la balise `style` grâce à des `@apply` 😉

2022-06-02 07:27 UTC, MrZyr0 requested changes

2022-06-02 07:27 UTC, MrZyr0 commented on src/components/QCard/QCard.vue
> +      <slot></slot>
```suggestion
      <slot/>
```

2022-06-02 07:27 UTC, MrZyr0 commented on src/components/QCard/QCard.vue
> +})
Ça sert à quoi finalement ?

2022-06-02 07:42 UTC, HugoBordais commented
![Screenshot_2022-06-02_at_09 39 51](https://user-images.githubusercontent.com/33489155/171579802-0908649a-5ca6-4150-8c8c-6c1b2e225311.png)

2022-06-02 07:49 UTC, zaktolba approved these changes

2022-06-02 07:56 UTC, MrZyr0 approved these changes

2022-06-02 07:57 UTC, merged