15 carousel
quiches-group/quichtify pull request #28
Opened 2022-06-01 08:04 UTC by nrgix2

# Feature/Carousel

>_Assigne_ : 
>Antoine MOUSSET

> _Task description :_
> This pull request enable to create a carousel with 2 props (title & content)

## Features

- [x] Create Carousel
- [x] Add props

2022-06-01 08:07 UTC, ChxGuillaume requested changes
Please make it your own.

2022-06-01 08:07 UTC, ChxGuillaume commented on package.json
> +    "vueperslides": "^3.3.2"
remove this

2022-06-01 08:07 UTC, ChxGuillaume commented on src/index.js
> +    Vue.component('CarouselVue', CarouselVue);
don't remove the hello world from exported components

2022-06-01 12:59 UTC, ChxGuillaume requested changes
Missing caourssel item

2022-06-01 12:59 UTC, ChxGuillaume commented on package.json
> +    "style-inject": "^0.3.0",
???

2022-06-01 13:00 UTC, ChxGuillaume commented
https://vuetifyjs.com/en/components/carousels/

2022-06-02 09:09 UTC, MrZyr0 submitted a review, later dismissed

2022-06-02 09:09 UTC, MrZyr0 commented on src/components/QCarousel/QCarousel.vue
> +    <slot> </slot>
```suggestion
    <slot />
```

2022-06-02 09:09 UTC, MrZyr0 commented on src/components/QCarousel/QCarouselItem.vue
> +    <slot></slot>
```suggestion
    <slot />
```

2022-06-02 10:13 UTC, ChxGuillaume requested changes

2022-06-02 10:13 UTC, ChxGuillaume commented on src/components/QCarousel/QCarousel.vue
> +    <button class="button" @click="selectItemFromIndex(state.selectedIndex + 1)">Aller à droite</button>
why forcing it ?

2022-06-02 10:13 UTC, ChxGuillaume commented on src/components/QCarousel/QCarousel.vue
> +})
??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

2022-06-02 10:13 UTC, ChxGuillaume commented on src/components/QCarousel/QCarousel.vue
> +}
tailwind?

2022-06-02 14:05 UTC, ChxGuillaume approved these changes

2022-06-02 14:16 UTC, merged