feat(snackbar): create custom snackbar
quiches-group/quichtify pull request #49
Opened 2022-06-09 21:09 UTC by Floberrot

custom color, variant and position for example

2022-06-09 22:31 UTC, ChxGuillaume requested changes
Maybe test you stuff more in your example (button to reopen it etc...)
Please use vModel
Please use Slots

In shorts, please use VUEJS FEATURES!!

2022-06-09 22:31 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +          <p class="text-snackbar" :class="colorTextClass">{{ message }}</p>
why not using a slot?

2022-06-09 22:31 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +              @click="Close">X
Is the q-btn necessary?

2022-06-09 22:31 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +    },
Should be required.

Should be V-Model (https://vuejs.org/api/built-in-directives.html#v-model)

2022-06-09 22:31 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +    },
as you should use slots, you shouldn't require textColor

2022-06-09 22:31 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +    },
Useles

2022-06-09 22:31 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +    }
??

https://www.youtube.com/watch?v=-1qju6V1jLM

2022-06-09 22:31 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +      }
why specific to top-center and bottom-center ?

Should be
top
bottom
left
right
and the variantes of them (botton-left, bottom-right, top-left, top-right)

2022-06-09 22:31 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +    }
as told above, useless

https://www.youtube.com/watch?v=-1qju6V1jLM

2022-06-09 22:31 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +  }
should use vmodel ($emit)

2022-06-09 22:32 UTC, ChxGuillaume requested changes

2022-06-09 22:32 UTC, ChxGuillaume commented on src/components/QSnackBar/QSnackBar.vue
> +      </q-row>
Why using qGrid ?

2022-06-09 22:32 UTC, ChxGuillaume commented
https://vuetifyjs.com/en/components/snackbars/#usage

https://www.youtube.com/watch?v=-1qju6V1jLM

2022-06-10 04:30 UTC, MaxenceMottard reviewed
Sorry but I prefer @Laroche-Nicolas's implementation of snackbar : #52.
There was a lack of communication and you both made the same component 😕

2022-06-10 05:24 UTC, Floberrot commented
> Maybe test you stuff more in your example (button to reopen it etc...) Please use vModel Please use Slots
> 
> In shorts, please use VUEJS FEATURES!!

Sorry but i'm trying to learn vuejs at the same time, so I can forget some things. You can close it, nicolas create a better snackbar

2022-06-10 07:04 UTC, closed without merging

2022-06-10 07:35 UTC, MaxenceMottard commented
There is no problem, it's just a pity to have spent time to make it not merge, I'm sorry 😕