Feature/sncakbar
quiches-group/quichtify pull request #52
Opened 2022-06-09 22:18 UTC by Laroche-Nicolas

2022-06-09 22:37 UTC, ChxGuillaume requested changes

2022-06-09 22:37 UTC, ChxGuillaume commented on src/components/QSnackbar/Example.vue
> +</template>
Did you enabled eslint?

2022-06-09 22:37 UTC, ChxGuillaume commented on src/components/QSnackbar/Example.vue
> +</style>
useless tag

2022-06-09 22:37 UTC, ChxGuillaume commented on src/components/QSnackbar/QSnackbar.vue
> +  },
use v-model
https://vuejs.org/api/built-in-directives.html#v-model

2022-06-09 22:37 UTC, ChxGuillaume commented on src/components/QSnackbar/QSnackbar.vue
> +  },
estlint

2022-06-09 22:37 UTC, ChxGuillaume commented on src/components/QSnackbar/QSnackbar.vue
> +  }
switch case ?

2022-06-09 22:37 UTC, ChxGuillaume commented on src/components/QSnackbar/QSnackbar.vue
> +      const validValues = ['bottom', 'bottom-left', 'bottom-right', 'top', 'top-left', 'top-right'];
Maybe add left and right?
Could be a good addition

2022-06-09 23:31 UTC, Laroche-Nicolas commented on src/components/QSnackbar/QSnackbar.vue
> +  }
👀

2022-06-10 04:23 UTC, MaxenceMottard commented
Pour moi il manque une props optionnel où on peut donner un temps pendant lequel la snackbar va rester ouverte et elle se ferme auto après le temps en param

2022-06-10 04:24 UTC, MaxenceMottard reviewed
Pour moi il manque une props optionnel où on peut donner un temps pendant lequel la snackbar va rester ouverte et elle se ferme auto après le temps en param

2022-06-11 17:18 UTC, MaxenceMottard approved these changes

2022-06-11 17:19 UTC, merged